In [1]:
import pandas as pd
import numpy as np

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

In [5]:
data = [i for i in range(10)]
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 벡터처럼 사용할 수 있는 numpy
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# 리스트를 사용할 때와 ndarray를 사용할 때의 차이
2 * data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
2 * a + b

array([12, 24, 36])

In [12]:
a == 2

array([False,  True, False])

In [13]:
(a == 2) & (b > 10)

array([False,  True, False])

In [14]:
b > 10

array([False,  True,  True])

In [28]:
L = [[i * 10 for i in range(1, 5)],[i * 10 for i in range(5, 9)]]
nl = np.array(L)

In [29]:
nl

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [30]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4 ,6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [31]:
a = np.array([[1,2,3,4,], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [33]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [42]:
x = np.array([i for i in range(1,21)])
# 1. 3의 배수 찾기.
print(x[x%3 == False])

# 2. 4로 나누면 1이 남는 수 찾기
print(x[x%4 == 1])

# 3. 3으로 나누어 떨이지고, 4로 나누면 1이 남는 수 찾기.
print(x[(x % 3 == False) & (x % 4) == 1])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[ 3  9 15]


In [44]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [45]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [46]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [47]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [48]:
x[0] + x[1]

3.0

In [49]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [50]:
x

array(['1', '2', '3'], dtype='<U1')

In [51]:
x[0] + x[1]

'12'

In [52]:
np.array([0, 1, -1, 0] / np.array([1, 0, 0, 0]))

c:\users\dm705\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\dm705\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [53]:
np.log(0)

c:\users\dm705\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [54]:
np.exp(-np.inf)

0.0

In [55]:
-np.inf

-inf

In [56]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [57]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
c = np.zeros((5, 2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [59]:
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [61]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [62]:
e = np.ones((2, 3, 4), dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [63]:
f = np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [64]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [67]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [68]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [69]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### numpy.logspace(start, end, num=개수, endpoint=True, base=10.0)

> `start ~ end` 사이의 로그 배율을 사용하여 개수만큼 생서어하여 배열로 반환  
> `endpoint`가 `True`일 경우 `end` 의 경우 마지막 값으로 사용하지 않는다.  
> `base`는 로그 값의 `간격`을 의미합니다.  

In [74]:
tmp = np.logspace(0, 1,num=10, endpoint=True, base=10.0)
tmp

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [79]:
np.logspace(0, 1, 10, endpoint=False, base=5.0)

array([1.        , 1.17461894, 1.37972966, 1.6206566 , 1.90365394,
       2.23606798, 2.6265278 , 3.08516931, 3.62389832, 4.25669961])

In [80]:
np.logspace(0, 1, 10, endpoint=True, base=5.0)

array([1.        , 1.19581317, 1.42996915, 1.70997595, 2.04481177,
       2.44521285, 2.92401774, 3.49657893, 4.18125515, 5.        ])

In [86]:
np.logspace(1, 3, num=10, endpoint=False, base=2.0)

array([2.        , 2.29739671, 2.63901582, 3.03143313, 3.48220225,
       4.        , 4.59479342, 5.27803164, 6.06286627, 6.96440451])

In [87]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
# -1은 조커(*) 처럼 사용 가능하다.
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [91]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [97]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [101]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [102]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [103]:
x

array([0, 1, 2, 3, 4])

In [104]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [108]:
a1 = np.ones((2, 3), dtype='i')
a1

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [109]:
a1.dtype

dtype('int32')

In [110]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [111]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [114]:
a3 = np.zeros([4, 3])
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
# import numpy as np
np.vstack([a1, a3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [116]:
np.vstack([a1, a2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [117]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [120]:
c1.shape

(3, 4)

In [121]:
c2.shape

(3, 4)

In [122]:
np.dstack([c1, c2]).shape

(3, 4, 2)

In [125]:
c = np.stack([c1, c2])
c.shape

In [126]:
c = np.stack([c1, c2])
c.shape

(2, 3, 4)